name: coverage
run-name: coverage

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  workflow_dispatch:

jobs:
  Coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare
        run: sudo apt install lcov

      - name: Build
        run: ./build-linux

      - name: Make
        run: make test_cutils/coverage CONFIG=Debug PLATFORM=x64 SHOW=false

      - name: Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: martis99/cutils
          files: ./bin/Debug-x64/tests/test_cutils/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@v2

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lcov.info
          path: ./bin/Debug-x64/tests/test_cutils/lcov.info
