name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Windows-MSBuild:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Generate solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build-win-x64.exe

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore .

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} .

    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\bin\${{matrix.configuration}}-${{matrix.platform}}\tests\test_cutils\test_cutils.exe
